name: garnet
channels:
  - conda-forge
  - mantid/label/nightly
  - oncat
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - pycifrw
  - h5py
  - lmfit
  - mantidworkbench
  - pytest
  - conda
  - qtpy
  - pyqt6
  - pyvista
  - scikit-learn
  - scikit-image
  - gemmi
  - qtawesome
  - qdarkstyle
  - pre-commit
  - black
  - pip:
    - pyoncat
