name: garnet
channels:
  - conda-forge
  - mantid/label/nightly
  - oncat
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - pycifrw
  - h5py
  - lmfit
  - mantidworkbench
  - pytest
  - conda
  - qtpy
  - pyvista
  - pyvistaqt
  - scikit-learn
  - scikit-image
  - gemmi
  - qtawesome
  - qdarkstyle
  - pre-commit
  - black
  - sphinx
  - sphinx-autodoc-typehints
  - pydata-sphinx-theme
  - numpydoc
  - pip:
    - pyoncat
